# Rust fmt workflow
# Github: https://www.github.com/lewisevans2007/workflows
# By: Lewis Evans

name: Rust fmt
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rust_fmt:
    name: Rust fmt
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          rustup component add rustfmt
      - name: Git pull
        run: |
          git pull
      - name: Format with Rust fmt
        run: |
          cargo fmt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format rust code with rustfmt"
          file_pattern: "*.rs"